#!/usr/bin/env bash

set -o nounset
set -o pipefail
set -o errexit

BOWTIE_IDX=$1
READ1=$2
READ2=$3
NUMTHREADS=$4
GENOMESIZE=$5
CHROMSIZE=$6
OUTPUTDIR=$7

MAPQ_THRESH=30

# trim adapters
# .fastq/.fastq.gz/.fq -> .trim.fastq
# assumes that trimAdapters outputs the R1/R2 output filenames 
# as the last 2 lines in stdout
trim_jobid=$(qrun trimAdapters -a "$READ1" -b "$READ2")

echo "Submitted adapter trimming job: ${trim_jobid}"

# submit alignment job, with more cores
align_jobid=$(
qrun -N alignATAC -hold_jid ${trim_jobid} -pe shm ${NUMTHREADS} -l h_rt=24:00:00 -l h_stack=10M \
    ATACpipeline-2 "$BOWTIE_IDX" "$NUMTHREADS" "$OUTPUTDIR" "$trim_jobid"
)

echo "Submitted alignment job: ${align_jobid}"

postprocess_jobid=$(qrun -N postprocessATAC -hold_jid ${align_jobid} -l h_vmem=8G -l h_rt=24:00:00 \
    ATACpipeline-3 "$GENOMESIZE" "$CHROMSIZE" "$OUTPUTDIR" "$MAPQ_THRESH" "$align_jobid"
)

echo "Submitted postprocessing job: ${postprocess_jobid}"

